#!/bin/bash
#
# Installation script which setup up an Debain 11 machine to use this
# vim configuration. 
#
# WARNING!!! 
# * This has only been tested on a limited number of machines running 
#   Debian 11 64-bit.
# * This is not a sophisticated installation script by any stretch 
#   of the imagination. 
# * I take no responsibility if this overwrites any configuration settings 
#   or otherwise messes up your system. 
#
# Maintainer: Xsbd
# Repository: https://github.com/Xsbd/vim-conf
#

CWD=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
DIR='templates autoload bundle thesaurus'
GIT='git --git-dir='$PWD'/.git'

echo "Installing required packages..."
sudo apt-get install vim git

echo "Installing Plugins"
$GIT submodule update --init --recursive

echo "Linking to customized configuration..."
if [ -f "~/.vim" ] ; then
  mv -n ~/.vim ~/.vim.original
fi
if [ -f "~/.vimrc" ] ; then
  mv -n ~/.vimrc ~/.vim.original
fi
mkdir ~/.vim
for i in $DIR
do
  cp -sir $CWD/$i ~/.vim/
done
ln -si $CWD/vimrc ~/.vimrc
